# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true


# Setup
title:               ./mickey.sh
tagline:             '--fun'
description:         'A man on the run ğŸƒ; a rollin' stone ğŸ‘¨â€ğŸ¤, a superstar â­ï¸ but I stay on the move. <a href="https://twitter.com/mickeypash" target="_blank">@mickeypash</a>'
url:                 http://mickey.sh
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mickey Pashov
  url:               https://twitter.com/mickeypash
  email:             pashov.m@gmail.com

# Custom vars
version:             1.0.1
